site_name: Databases
site_url: http://sillevl.github.io/course-databases/
repo_url: https://github.com/sillevl/course-databases
repo_name: GitHub
site_author: Sille Van Landschoot
theme: readthedocs
markdown_extensions:
 - admonition
 - attr_list
 - def_list
pages:
  - Home: index.md
  - Setting up example databases: creating_forta_database.md
  - MySQL introduction: mysql-introduction.md
  - Retreiving data: retreiving-data.md
  - Sorting retreived data: sorting-retreived-data.md
  - Filtering data: filtering-data.md
  - Searching using Regular Expressions: searching-using-regular-expressions.md
  - Calculated fields: calculated-fields.md
  - Data manipulation: data-manipulation.md
  - Summarizing data: summarizing-data.md
  - Grouping data: grouping-data.md
  - Working with subqueries: subqueries.md
  - Joining tables: joins.md
  - Combining queries: combining-queries.md
  - Full-text searching: full-text-searching.md
  - Inserting data: inserting-data.md
  - Updating and deleting data: update-and-delete.md
  - Creating and manipulating tables: creating-and-manipulating-tables.md
  - Using views: views.md
  - Stored procedures: stored-procedures.md
  - Using cursors: cursors.md
  - Using triggers: triggers.md
  - Managing transaction processing: transactions.md
  - Globalization and localization: globalization-and-localization.md
  - Managing database users: database-users.md
  - Database maintenance: database-maintenance.md
  - Concurrency: concurrency.md
  - Storing passwords: passwords.md
  - PHP PDO's: php-pdo.md
  - Entity-Relation Diagram: er-diagram.md
  - MySQL datatypes: mysql-datatypes.md
